### PR TITLE
Changes Done - Added Data 

### PR DESCRIPTION
**Pull request by parag477**
Commited Changes, Added New Data and Pushed the Repo.

### CODE REVIEW

**Comment by parag477** [comment]
Done

**Comment by srashtisj** [comment]
Hi Parag! - You did asked me for Google Developer sticker in the event? Right?

**Comment by parag477** [comment]
Yes mam, I had asked you for that.

**Comment by srashtisj** [comment]
I do have it - you can take it from me in next event. :)
image

**Comment by parag477** [comment]
Very thank you mam!!

**Pull request merged**
